# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: versionOverride
      displayName: Version to deploy
      type: string
      default: ''
    - name: tag
      displayName: release tag
      type: string
      default: ''

trigger: none

pool:
    vmImage: ubuntu-latest

resources:
    pipelines:
        - pipeline: accessibility-insights-action-ci
          source: accessibility-insights-action-ci

variables:
    - name: extensionVersionOverride
      value: ${{ parameters.versionOverride }}
    - name: tag
      value: ${{ parameters.tag }}

stages:
    - stage: package_publish_staging
      variables:
          - group: ado-extension-staging
      jobs:
          - template: release-template.yaml
            parameters:
                environment: ado-extension-staging

    - stage: create_release_tag
      jobs:
          - job: 'CreateReleaseTag'
            steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                      source: 'specific'
                      runVersion: 'specific'
                      project: $(resources.pipeline.accessibility-insights-action-ci.projectID)
                      pipeline: $(resources.pipeline.accessibility-insights-action-ci.pipelineID)
                      runId: $(resources.pipeline.accessibility-insights-action-ci.runID)
                      artifact: ado-extension-drop
                      path: '$(System.DefaultWorkingDirectory)/ado-extension-drop'

                - task: GitHubRelease@1
                  displayName: 'GitHub release (create)'
                  inputs:
                      tag: '$(tag)'
                      tagSource: userSpecifiedTag
                      gitHubConnection: 'ada-cat-github-repo-access'
                      target: $(resources.pipeline.accessibility-insights-action-ci.sourceCommit)
                      assets: '$(System.DefaultWorkingDirectory)/ado-extension-drop/NOTICE.html'

    - stage: package_publish_prod
      variables:
          - group: ado-extension-prod
      jobs:
          - template: release-template.yaml
            parameters:
                environment: ado-extension-prod
